spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bath
    username: "root"
    password: "wgxh5197"
  thymeleaf:
     prefix: classpath:/templates/
     cache: false
     encoding: UTF-8
     suffix: .html
     mode: LEGACYHTML5
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  devtools:
    restart.additional-paths: src/main/java
server:
  port: 8086
  tomcat:
    uri-encoding: UTF-8
